name: "Load Today's Light!"

on:
  # Run once per day at 00:15 UTC
  schedule:
    - cron: '15 0 * * *'

jobs:
  load-todays-light:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup GitHub User Details
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GPG_USER: ${{ secrets.GPG_USER }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PUB: ${{ secrets.SSH_PUB }}
        run: |
          /bin/bash <(/bin/curl -s https://raw.githubusercontent.com/vdm-io/github-user/master/src/setup.sh) \
            --gpg-key "$GPG_KEY" \
            --gpg-user "$GPG_USER" \
            --ssh-key "$SSH_KEY" \
            --ssh-pub "$SSH_PUB" \
            --git-user "$GIT_USER" \
            --git-email "$GIT_EMAIL"

      - name: Clone Daily Light Repository
        run: |
          /bin/git clone git@github.com:trueChristian/daily-light.git daily_light

      - name: Build Today’s Light
        run: |
          cd daily_light
          /bin/bash ./src/today.sh

